# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TarangGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1061, 651))
        self.tabWidget.setObjectName("tabWidget")
        self.program = QtWidgets.QWidget()
        self.program.setObjectName("program")
        self.program_kind_label = QtWidgets.QLabel(self.program)
        self.program_kind_label.setGeometry(QtCore.QRect(70, 60, 161, 17))
        self.program_kind_label.setObjectName("program_kind_label")
        self.label = QtWidgets.QLabel(self.program)
        self.label.setGeometry(QtCore.QRect(240, 60, 16, 17))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.program)
        self.comboBox.setGeometry(QtCore.QRect(250, 54, 191, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.program)
        self.comboBox_2.setGeometry(QtCore.QRect(250, 94, 191, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.program_basis_type_label = QtWidgets.QLabel(self.program)
        self.program_basis_type_label.setGeometry(QtCore.QRect(70, 100, 161, 17))
        self.program_basis_type_label.setObjectName("program_basis_type_label")
        self.label_2 = QtWidgets.QLabel(self.program)
        self.label_2.setGeometry(QtCore.QRect(240, 100, 16, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.program)
        self.label_3.setGeometry(QtCore.QRect(240, 140, 16, 17))
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.program)
        self.comboBox_3.setGeometry(QtCore.QRect(250, 134, 191, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.program_iter_or_diag_label = QtWidgets.QLabel(self.program)
        self.program_iter_or_diag_label.setGeometry(QtCore.QRect(70, 140, 161, 17))
        self.program_iter_or_diag_label.setObjectName("program_iter_or_diag_label")
        self.label_4 = QtWidgets.QLabel(self.program)
        self.label_4.setGeometry(QtCore.QRect(240, 180, 16, 17))
        self.label_4.setObjectName("label_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.program)
        self.comboBox_4.setGeometry(QtCore.QRect(250, 174, 191, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.program_alias_option_label = QtWidgets.QLabel(self.program)
        self.program_alias_option_label.setGeometry(QtCore.QRect(70, 180, 161, 17))
        self.program_alias_option_label.setObjectName("program_alias_option_label")
        self.label_5 = QtWidgets.QLabel(self.program)
        self.label_5.setGeometry(QtCore.QRect(240, 216, 16, 17))
        self.label_5.setObjectName("label_5")
        self.program_integration_scheme_label = QtWidgets.QLabel(self.program)
        self.program_integration_scheme_label.setGeometry(QtCore.QRect(70, 216, 161, 17))
        self.program_integration_scheme_label.setObjectName("program_integration_scheme_label")
        self.comboBox_5 = QtWidgets.QComboBox(self.program)
        self.comboBox_5.setGeometry(QtCore.QRect(250, 400, 191, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_6 = QtWidgets.QLabel(self.program)
        self.label_6.setGeometry(QtCore.QRect(240, 250, 16, 17))
        self.label_6.setObjectName("label_6")
        self.program_LES_switch_label = QtWidgets.QLabel(self.program)
        self.program_LES_switch_label.setGeometry(QtCore.QRect(70, 250, 161, 17))
        self.program_LES_switch_label.setObjectName("program_LES_switch_label")
        self.label_7 = QtWidgets.QLabel(self.program)
        self.label_7.setGeometry(QtCore.QRect(250, 250, 67, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.program)
        self.label_8.setGeometry(QtCore.QRect(360, 280, 67, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.program_apply_strong_realitycond_alltime_switch_label = QtWidgets.QLabel(self.program)
        self.program_apply_strong_realitycond_alltime_switch_label.setGeometry(QtCore.QRect(70, 280, 281, 17))
        self.program_apply_strong_realitycond_alltime_switch_label.setObjectName("program_apply_strong_realitycond_alltime_switch_label")
        self.label_9 = QtWidgets.QLabel(self.program)
        self.label_9.setGeometry(QtCore.QRect(350, 280, 16, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.program)
        self.label_10.setGeometry(QtCore.QRect(360, 310, 67, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.program_apply_weak_realitycond_switch_alltime_switch_label = QtWidgets.QLabel(self.program)
        self.program_apply_weak_realitycond_switch_alltime_switch_label.setGeometry(QtCore.QRect(70, 310, 281, 17))
        self.program_apply_weak_realitycond_switch_alltime_switch_label.setObjectName("program_apply_weak_realitycond_switch_alltime_switch_label")
        self.label_11 = QtWidgets.QLabel(self.program)
        self.label_11.setGeometry(QtCore.QRect(350, 310, 16, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.program)
        self.label_12.setGeometry(QtCore.QRect(250, 340, 67, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.program_low_diemnsional_switch_label = QtWidgets.QLabel(self.program)
        self.program_low_diemnsional_switch_label.setGeometry(QtCore.QRect(70, 340, 171, 17))
        self.program_low_diemnsional_switch_label.setObjectName("program_low_diemnsional_switch_label")
        self.label_13 = QtWidgets.QLabel(self.program)
        self.label_13.setGeometry(QtCore.QRect(240, 340, 16, 17))
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.program)
        self.label_16.setGeometry(QtCore.QRect(240, 370, 16, 17))
        self.label_16.setObjectName("label_16")
        self.program_two_dimension_label = QtWidgets.QLabel(self.program)
        self.program_two_dimension_label.setGeometry(QtCore.QRect(70, 370, 171, 17))
        self.program_two_dimension_label.setObjectName("program_two_dimension_label")
        self.label_17 = QtWidgets.QLabel(self.program)
        self.label_17.setGeometry(QtCore.QRect(250, 370, 67, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.program_dt_option_label = QtWidgets.QLabel(self.program)
        self.program_dt_option_label.setGeometry(QtCore.QRect(70, 410, 171, 17))
        self.program_dt_option_label.setObjectName("program_dt_option_label")
        self.label_19 = QtWidgets.QLabel(self.program)
        self.label_19.setGeometry(QtCore.QRect(240, 410, 16, 17))
        self.label_19.setObjectName("label_19")
        self.comboBox_6 = QtWidgets.QComboBox(self.program)
        self.comboBox_6.setGeometry(QtCore.QRect(250, 210, 191, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.program_helicity_switch_label = QtWidgets.QLabel(self.program)
        self.program_helicity_switch_label.setGeometry(QtCore.QRect(70, 440, 171, 17))
        self.program_helicity_switch_label.setObjectName("program_helicity_switch_label")
        self.label_18 = QtWidgets.QLabel(self.program)
        self.label_18.setGeometry(QtCore.QRect(250, 440, 67, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.program)
        self.label_20.setGeometry(QtCore.QRect(240, 440, 16, 17))
        self.label_20.setObjectName("label_20")
        self.program_sincostr_switch = QtWidgets.QLabel(self.program)
        self.program_sincostr_switch.setGeometry(QtCore.QRect(70, 470, 171, 17))
        self.program_sincostr_switch.setObjectName("program_sincostr_switch")
        self.label_22 = QtWidgets.QLabel(self.program)
        self.label_22.setGeometry(QtCore.QRect(240, 470, 16, 17))
        self.label_22.setObjectName("label_22")
        self.lineEdit = QtWidgets.QLineEdit(self.program)
        self.lineEdit.setGeometry(QtCore.QRect(250, 470, 171, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.help = QtWidgets.QStackedWidget(self.program)
        self.help.setGeometry(QtCore.QRect(550, 70, 491, 511))
        self.help.setObjectName("help")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.textBrowser = QtWidgets.QTextBrowser(self.page)
        self.textBrowser.setGeometry(QtCore.QRect(5, 1, 481, 551))
        self.textBrowser.setObjectName("textBrowser")
        self.help.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 491, 511))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.help.addWidget(self.page_2)
        self.horizontalSlider = QtWidgets.QSlider(self.program)
        self.horizontalSlider.setGeometry(QtCore.QRect(290, 440, 51, 16))
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setMaximum(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_21 = QtWidgets.QLabel(self.program)
        self.label_21.setGeometry(QtCore.QRect(350, 440, 67, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.help_label = QtWidgets.QLabel(self.program)
        self.help_label.setGeometry(QtCore.QRect(710, 30, 31, 16))
        self.help_label.setObjectName("help_label")
        self.help_dropdown = QtWidgets.QComboBox(self.program)
        self.help_dropdown.setGeometry(QtCore.QRect(760, 20, 191, 31))
        self.help_dropdown.setObjectName("help_dropdown")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.help_dropdown.addItem("")
        self.label_24 = QtWidgets.QLabel(self.program)
        self.label_24.setGeometry(QtCore.QRect(750, 30, 16, 17))
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.program, "")
        self.field_tab = QtWidgets.QWidget()
        self.field_tab.setObjectName("field_tab")
        self.tabWidget.addTab(self.field_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.help.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tarang GUI"))
        self.program_kind_label.setText(_translate("MainWindow", "kind"))
        self.label.setText(_translate("MainWindow", ":"))
        self.comboBox.setItemText(0, _translate("MainWindow", "FLUID_INCOMPRESS"))
        self.comboBox.setItemText(1, _translate("MainWindow", "SCALAR_INCOMPRESS"))
        self.comboBox.setItemText(2, _translate("MainWindow", "RBC"))
        self.comboBox.setItemText(3, _translate("MainWindow", "STRATIFIED"))
        self.comboBox.setItemText(4, _translate("MainWindow", "MRBC"))
        self.comboBox.setItemText(5, _translate("MainWindow", "MHD_INCOMPRESS"))
        self.comboBox.setItemText(6, _translate("MainWindow", "KEPLERIAN"))
        self.comboBox.setItemText(7, _translate("MainWindow", "MHD_SCALAR_INCOMPRESS"))
        self.comboBox.setItemText(8, _translate("MainWindow", "MHD_ASTRO_INCOMPRESS"))
        self.comboBox.setItemText(9, _translate("MainWindow", "GP"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "FFF"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "SFF"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "SSF"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "SSS"))
        self.program_basis_type_label.setText(_translate("MainWindow", "basis_type"))
        self.label_2.setText(_translate("MainWindow", ":"))
        self.label_3.setText(_translate("MainWindow", ":"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "ITERATION"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "DIAGNOSTICS"))
        self.program_iter_or_diag_label.setText(_translate("MainWindow", "iter_or_diag"))
        self.label_4.setText(_translate("MainWindow", ":"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "DEALIAS"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "ALIAS"))
        self.program_alias_option_label.setText(_translate("MainWindow", "alias_option"))
        self.label_5.setText(_translate("MainWindow", ":"))
        self.program_integration_scheme_label.setText(_translate("MainWindow", "integration_scheme"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "FIXED"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "CFL"))
        self.label_6.setText(_translate("MainWindow", ":"))
        self.program_LES_switch_label.setText(_translate("MainWindow", "LES_switch"))
        self.label_7.setText(_translate("MainWindow", "false"))
        self.label_8.setText(_translate("MainWindow", "false"))
        self.program_apply_strong_realitycond_alltime_switch_label.setText(_translate("MainWindow", "apply_strong_realitycond_alltime_switch"))
        self.label_9.setText(_translate("MainWindow", ":"))
        self.label_10.setText(_translate("MainWindow", "false"))
        self.program_apply_weak_realitycond_switch_alltime_switch_label.setText(_translate("MainWindow", "apply_weak_realitycond_alltime_switch"))
        self.label_11.setText(_translate("MainWindow", ":"))
        self.label_12.setText(_translate("MainWindow", "false"))
        self.program_low_diemnsional_switch_label.setText(_translate("MainWindow", "low_dimensional_switch"))
        self.label_13.setText(_translate("MainWindow", ":"))
        self.label_16.setText(_translate("MainWindow", ":"))
        self.program_two_dimension_label.setText(_translate("MainWindow", "two_dimension"))
        self.label_17.setText(_translate("MainWindow", "false"))
        self.program_dt_option_label.setText(_translate("MainWindow", "dt_option"))
        self.label_19.setText(_translate("MainWindow", ":"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "RK4"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "RK4"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "EULER"))
        self.program_helicity_switch_label.setText(_translate("MainWindow", "helicity_switch"))
        self.label_18.setText(_translate("MainWindow", "true"))
        self.label_20.setText(_translate("MainWindow", ":"))
        self.program_sincostr_switch.setText(_translate("MainWindow", "sincostr_switch"))
        self.label_22.setText(_translate("MainWindow", ":"))
        self.lineEdit.setText(_translate("MainWindow", "FFF"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">kind</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">basis_type</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "false"))
        self.help_label.setText(_translate("MainWindow", "Help"))
        self.help_dropdown.setItemText(0, _translate("MainWindow", "kind"))
        self.help_dropdown.setItemText(1, _translate("MainWindow", "basis_type"))
        self.help_dropdown.setItemText(2, _translate("MainWindow", "iter_or_diag"))
        self.help_dropdown.setItemText(3, _translate("MainWindow", "alias_option"))
        self.help_dropdown.setItemText(4, _translate("MainWindow", "integration_scheme"))
        self.help_dropdown.setItemText(5, _translate("MainWindow", "LES_switch"))
        self.help_dropdown.setItemText(6, _translate("MainWindow", "apply_strong_realitycond_alltime_switch"))
        self.help_dropdown.setItemText(7, _translate("MainWindow", "apply_weak_realitycond_alltime_switch"))
        self.help_dropdown.setItemText(8, _translate("MainWindow", "low_dimensional_switch"))
        self.help_dropdown.setItemText(9, _translate("MainWindow", "two_dimensional_switch"))
        self.help_dropdown.setItemText(10, _translate("MainWindow", "two_dimension"))
        self.help_dropdown.setItemText(11, _translate("MainWindow", "dt_option"))
        self.help_dropdown.setItemText(12, _translate("MainWindow", "helicity_switch"))
        self.help_dropdown.setItemText(13, _translate("MainWindow", "sincostr_switch"))
        self.label_24.setText(_translate("MainWindow", ":"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.program), _translate("MainWindow", "Program"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.field_tab), _translate("MainWindow", "Field"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

